### ISSUE TITLE
[Feature] 디렉토리 구조랑 스타일파일 분리, layout 컴포넌트 수정

### ISSUE THREAD

**Issue by Goldchae** [KakaoTech-BootCamp-Team-2/Kaboo-Connection-Front#32]
## 🛠 Issue
<!— 이슈에 대해 간략하게 설명해주세요(글, 사진) —>
```
KABOO_CONNECTION-FRONT/
│
├── public/                 # 정적 파일들이 위치하는 곳 
│
├── src/                    # 소스 코드가 위치하는 곳
│   ├── assets/             # 이미지, 폰트, 스타일 등 정적 자산
│   ├── components/         # 재사용 가능한 컴포넌트
│   ├── pages/              # 각 라우트에 해당하는 페이지 컴포넌트
│   ├── hooks/              # 커스텀 훅
│   ├── constants/          # 공통적으로 사용되는 상수들을 정의한 파일
│   ├── stores/             # Zustand 상태관리
│   ├── services/           # api 관련 로직의 모듈 파일, auth와 같이 인증과 관련된 파일
│   ├── utils/              # 정규표현식 패턴이나 공통함수 등 공통으로 사용하는 유틸 파일
│   └── config/             # 여러개의 config 파일
│
└── package.json            # 프로젝트 설정 및 의존성 목록
```
컴포넌트 스타일,구조 분리
```
{컨포넌트이름}.styled.js : 스타일
{컨포넌트이름}.js : 구조
```

## 📝 To-do
<!— 진행할 작업에 대해 자세히 적어주세요 —>
- [x] 디렉토리 구조 수정
- [x] 스타일 파일 분리
- [x] 레이아웃 컴포넌트 합치고 수정
