### ISSUE TITLE
[Feature] PeopleListComponents 관련 컴포넌트들 + 페이지 구현

### ISSUE THREAD

**Issue by Goldchae** [KakaoTech-BootCamp-Team-2/Kaboo-Connection-Front#35]
## 🛠 Issue
<!— 이슈에 대해 간략하게 설명해주세요(글, 사진) —>
- 사람들 목록이 뜨는 페이지를 구현합니다
<img width="397" alt="스크린샷 2024-08-14 오후 12 10 37" src="https://github.com/user-attachments/assets/ffae3bfc-03c6-4295-96cb-70b194554e25">
이거욤

## 📝 To-do
<!— 진행할 작업에 대해 자세히 적어주세요 —>
- [ ] PeopleListComponents 페이지 구현
- [ ] PeopleListComponents용 카드 컴포넌트 구현
- [ ] PeopleListComponents용 레이아웃 박스 컴포넌트 구현
